# Setup
title:        OpenAI Gym projects
tagline:      A place where I implement and test RL algorithms in OpenAI environments
baseurl:
paginate:     1
repository:   jchen114/OpenAIGym
markdown:     redcarpet

# About/contact
author:
  name:       Jacob Chen
  url:        http://chenjacob.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
